Update for vm_fault_t
When compiling for Linux 5.4:

error: initialization of 'vm_fault_t (*)(struct vm_fault *)' {aka 'unsigned int (*)(struct vm_fault *)'} from incompatible pointer type 'int (*)(struct vm_fault *)' [-Werror=incompatible-pointer-types]
|   108 |     .fault = &fbtap_vma_fault

Switch to vm_fault_t and add a compatibility define.

Signed-off-by: Jason Andryuk <jandryuk@gmail.com>